language: rust
dist: bionic

addons:
    apt:
        packages:
            - libssl-dev

cache: cargo
rust:
  - stable

before_script: |
    cargo install cargo-tarpaulin

script:
- cargo clean
- cargo build --all
- cargo test --all

after_success: |
     cargo tarpaulin --all --out Xml
     bash <(curl -s https://codecov.io/bash)
